#ifndef APPCOLLECTION_GLOBAL_H
#define APPCOLLECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(APPCOLLECTION_LIBRARY)
#  define APPCOLLECTION_EXPORT Q_DECL_EXPORT
#else
#  define APPCOLLECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // APPCOLLECTION_GLOBAL_H
